default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: ""

development:
  <<: *default
  database: anichase_development

test:
  <<: *default
  database: anichase_test

production:
  <<: *default
  database: anichase_production
  username: postgres
  password: <%= ENV['ANICHASE_DATABASE_PASSWORD'] %>